//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHoa.Module.Master {
    
    
    public partial class MFooter {
        
        /// <summary>
        /// MLienHe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BanHoa.Module.MLienHe MLienHe;
        
        /// <summary>
        /// MMangXaHoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BanHoa.Module.MMangXaHoi MMangXaHoi;
        
        /// <summary>
        /// MLuotTruyCap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BanHoa.Module.MLuotTruyCap MLuotTruyCap;
    }
}
